backend:
  name: github # Or gitlab
  repo: abhinavkrin/avitechlab # Your username and repository
  branch: main # Branch to use
  base_url: https://us-central1-development-and-test-292807.cloudfunctions.net/ # The base URL for your Firebase Function
  auth_endpoint: /oauth/auth # The path to the OAuth endpoint of the function

publish_mode: editorial_workflow
media_folder: "/public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}{{minute}}{{second}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Excerpt", name: "excerpt", widget: "text", default: ""}
  - name: "projects"
    label: "Projects"
    folder: "_posts/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}{{minute}}{{second}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string", required: true }
      - {label: "Description", name: "desc", widget: "text", required: true }
      - {label: "Link", name: "link", widget: "string", default: "" }
      - {label: "Icon", name: "icon", widget: "image", allow_multiple: false, required: true }
      - {label: "In Development?", name: "in_dev", widget: "boolean", default: false }