import Head from 'next/head'
import Image from 'next/image'
import Footer from '../Components/Footer'
import Header from '../components/Header'
import AboutSection from '../components/home/AboutSection'
import IntroSection from '../components/home/IntroSection'
import styles from '../styles/pages/Home.module.scss'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <IntroSection/>
      <AboutSection/>
      <Footer/>
    </>
  )
}
