import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Header from '../components/Header'
import AboutSection from '../components/home/AboutSection'
import IntroSection from '../components/home/IntroSection'
import ProjectSection from '../components/home/ProjectSection.js'
import SkillSection from '../components/home/SkillSection'
import { getAllProjects } from '../lib/projects'
import styles from '../styles/pages/Home.module.scss'
export default function Home({projects}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isHome={true}/>
      <IntroSection/>
      <AboutSection/>
      <div style={{
          background: "var(--bs-white-grey-darker)",
          width: "100%", 
          margin: "0px", 
          padding: "5px 0px", 
          boxShadow: "inset 0 0px 5px rgba(0,0,0,0.2) "
        }}>
        <SkillSection/>
        <hr className={styles.divider}/>
        <ProjectSection projects={projects}/>
      </div>
      <Footer/>
    </>
  )
}


export async function getStaticProps(context){
  let projects = [];
  try {
    projects = (await getAllProjects()).map(pr => ({
      ...pr.attributes
    }));
  }
  catch(e){
    console.error(e);
  }
  return {
    props: {
      projects
    }
  }
}